### ISSUE TITLE
Numbers that don't work.

### ISSUE THREAD

**Issue by christianp** [christianp/sum-of-palindromes#5]
I'm collecting reports of numbers that don't give the expected result.

* 10300003, 10300013 (#1)
* 10420275 (#3)
* 12256004 (#4)
* 12281967

**Comment by christianp** [comment]
These now all work, and I've checked everything up to 10^8.

**Comment by primetimer** [comment]
Clever solution. I have checked some critical cases far beyond 10^8 and everything is fine.
